---
baseURL: https://seancollins.io
title: Sean Collins
paginate: 5
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
params:
  env: development
  title: Sean Collins
  description: ''
  author: Me
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false
  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"
  label:
    text: Sean Collins
    iconHeight: 35
  profileMode:
    enabled: false
    title: Sean Collins
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
    - name: Posts
      url: posts
    - name: Tags
      url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog
  socialIcons:
  - name: linkedin
    url: https://linkedin.com/in/theseancollins
  - name: github
    url: https://github.com/thehouseplant
  - name: twitter
    url: https://twitter.com/__seancollins
  analytics:
    google:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
    - title
    - permalink
    - summary
    - content
menu:
  main:
  - url: "/categories/"
    name: Categories
    weight: 1
    identifier: categories
  - url: "/tags/"
    name: Tags
    weight: 2
    identifier: tags
